### PR TITLE
Access webcam

### PR DESCRIPTION
**Pull request by jandrewtorres**
#4 Added a quick webcam access notebook. Take a selfie and apply filters.

### CODE REVIEW

**Comment by djbarnwal** [comment]
Hi @jandrewtorres, this PR has got your other Pull Requests' changes as well. It would be great if you could put the most recent commits and edit the PR so it's just those changes.

Best practice is to create a new branch from master for each PR you're going to open. Then rebase as needed, depending on the activity on master.

**Comment by jandrewtorres** [comment]
@djbarnwal Oops, thank you. Corrected with new commit.

**Comment by bcolloran** [comment]
Hmm, this example isn't working for me on FF (for our featured example notebooks, it will be important to test on at least FF and Chrome). I don't think this is the problem, but it looks like you're using webkit only css styles. Are there unprefixed versions that work in all browsers? Or perhaps other ways of accomplishing this objective?

Also FWIW, I did notice this console message on Chrome:
`[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.`

Cool notebook!

**Comment by jandrewtorres** [comment]
@bcolloran Thank you. Just pushed a commit that resolves both the FF compatibility and Chrome console warning issues. Ready for review.

**Comment by jandrewtorres** [comment]
@bcolloran This is a side effect of opening the file on your computer, with the file:// prefix. When served from https it should work. Unfortunately since we cannot import notebooks yet, it is hard to test. I just copied and pasted the code I wrote into a new notebook on https://iodide-project.github.io/master/  to test and it works fine. Reference: https://stackoverflow.com/questions/19914289/webcam-permission-request-doesnt-work-with-local-files

**Pull request merged**
