### PR TITLE
WIP: World Happiness Report

### PR DESCRIPTION
**Pull request by djbarnwal**
This example notebook is in progress. Until now, the outputs of various cells are manipulated to suit the Presentation mode (due to the dark theme). Thus, to see the notebook execute the cells sequentially and head over to Presentation mode.

The notebook can be viewed at - https://iodide-project.github.io/master/?url=https://raw.githubusercontent.com/djbarnwal/iodide-examples/28c2f4cb82409bd6b482cadc3a63cfd8fc9b4934/world-happiness-report-2018.html

To Do - 

- [X] Add inferences and more plots
- [X] Make outputs fitting for command view
- [ ] Proofread
- [ ] Clean up
- [ ] Make notebook work for 'Run all cells'(?)

### CODE REVIEW

**Comment by bcolloran** [comment]
This is a great notebook @djbarnwal! @hamilton has been working on some stuff that you may be able to use to get the "run all cells" functionality to behave as desired. @hamilton can you point @djbarnwal at you iodide.evalQueue docs/examples?

**Comment by hamilton** [comment]
@djbarnwal I'm planning on writing a fuller tutorial on how to synchronize cell execution in the async context (time is my enemy), but I think [this notebook](https://iodide-project.github.io/master/?gist=hamilton/ff2685729f67cdb6ea0035cdd9cb992c) should give you what you need to make things work with run-all-cells.

**Comment by hamilton** [comment]
Great notebook, btw!

**Comment by bcolloran** [comment]
@djbarnwal -- i'm going to go ahead and merge this right now, but please submit another PR with your next batch of changes when they are ready.

**Pull request merged**
