### PR TITLE
Optimized Bubble sort, fix for #23

### PR DESCRIPTION
**Pull request by imshubhamsingh**
As pointed out by @dsblank, I've fixed the bubble sort, and now I'll run one iteration if the data is already sorted.

### CODE REVIEW

**Comment by imshubhamsingh** [comment]
@dsblank Time Complexity of selection sort is always n(n - 1)/2, whereas insertion sort has better time complexity as its worst case complexity is n(n - 1)/2. Generally it will take **lesser or equal comparisons** then n(n - 1)/2.

**Comment by imshubhamsingh** [comment]
@dsblank the below gif show the best, avg, and worst case of the 3 sorting algos ran 2 time (one before sort and one after sort). The time difference is only because of color changes in the bar, and as far as the insertion sorting does't show comparison on re-sort the sorted array. I've fixed that.

Best Case:
best case

Average Case: 
avgcase

Worst Case: 
w

I hope this will clear all the issues that you raised.

**Comment by dsblank** [comment]
Thanks for taking care of these details!

> The time difference is only because of color changes in the bar, 

I think this basic issue needs to be examined carefully. Part of the point in showing these algorithms is to help explain and gain an intuitive understanding of their complexity. However, if there are artifacts of comparison based on the time of coloring, it may lead to confusion, rather than enlightenment.

I strongly encourage you to make sure that two algorithms that take the same number of comparisons take the same amount of rendering time. Otherwise, the whole point is lost.

**Comment by imshubhamsingh** [comment]
I understand that, the number of comparison are the same, but rendering time is little different due to the rendering process of the  D3.js, JavaScript library for visualizing data. I cannot help with that at the moment.

**Comment by bcolloran** [comment]
nice job @imshubhamsingh :-) i'm going to merge this, but of course keep the improvements coming if you have more in mind! :-)

**Pull request merged**
