### PR TITLE
Remove warning to wait in Python demo

### PR DESCRIPTION
**Pull request by mdboom**
Merge after https://github.com/iodide-project/pyodide/pull/27 is merged.

### CODE REVIEW

**Comment by hamilton** [comment]
This will work when you hit "run all cells" as of right now, and as soon as iodide-project/iodide#570 we can more reliably remove it for all circumstances.

**Comment by hamilton** [comment]
@mdboom 570 merged :) I noticed that I got an error when running the pyodide example. I'm guessing this is the ill-fated cdn issue we're bumping up against.

**Comment by mdboom** [comment]
Yep.  It sure is.  I'm planning on just rolling it back to a pre-pandas version.

**Comment by bcolloran** [comment]
@mdboom  do let me know when you have another hosting solution figured out and you want a redirect from iodide.io.

(ps: if it would be helpful to you, i'm sure @hamilton would be willing to make introductions with jason (and probably also willing to help drive that process forward?))

**Comment by mdboom** [comment]
In the meantime, I just rolled things back to the pre-Pandas state, so it's working again.

**Pull request closed without merging**
